live_config_reload = true

[window]
	padding = { x=5, y=5 }
    dynamic_padding = true
	opacity = 0.95
	decorations_theme_variant = "Dark"
    dynamic_title = true

[font]
	normal = { family = "FiraCode Nerd Font", style = "bold"}
	size = 13 

[colors.primary]
#    background = '0x282828'
    foreground = '0xebdbb2'
	background = "0x000000"
#	foreground = "0xd8d8d8"

  # Normal colors
[colors.normal]
    black =   '0x282828'
    red =     '0xcc241d'
    green =   '0x98971a'
    yellow =  '0xd79921'
    blue =    '0x458588'
    magenta = '0xb16286'
    cyan =    '0x689d6a'
    white =   '0xa89984'

  # Bright colors
[colors.bright]
    black =   '0x928374'
    red =     '0xfb4934'
    green =   '0xb8bb26'
    yellow =  '0xfabd2f'
    blue =    '0x83a598'
    magenta = '0xd3869b'
    cyan =    '0x8ec07c'
    white =   '0xebdbb2'

[bell]
    duration = 0
