live_config_reload = true

[window]
	padding = { x=5, y=5 }
    dynamic_padding = true
	opacity = 0.85
	decorations_theme_variant = "Dark"
    dynamic_title = true

[font]
	normal = { family = "Hack Nerd Font Mono", style = "bold"}
	size = 13 

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
#background = '#1a1b26'
background = '#000000'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

#
# Gruvbox 
#
#[colors.primary]
##    background = '0x282828'
#    foreground = '0xebdbb2'
#	background = "0x000000"
##	foreground = "0xd8d8d8"
#
#  # Normal colors
#[colors.normal]
#    black =   '0x282828'
#    red =     '0xcc241d'
#    green =   '0x98971a'
#    yellow =  '0xd79921'
#    blue =    '0x458588'
#    magenta = '0xb16286'
#    cyan =    '0x689d6a'
#    white =   '0xa89984'
#
#  # Bright colors
#[colors.bright]
#    black =   '0x928374'
#    red =     '0xfb4934'
#    green =   '0xb8bb26'
#    yellow =  '0xfabd2f'
#    blue =    '0x83a598'
#    magenta = '0xd3869b'
#    cyan =    '0x8ec07c'
#    white =   '0xebdbb2'

[bell]
    duration = 0
